### ISSUE TITLE
CSS for Compare tool orientation 

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#156]
We need guidance (well specifically @shoeswat ) to be able to fix the legend on the holos instance of the Compare tool. Let us know the best way to interact on this-- may be a short call or email, whatever is easiest. See below:

![screenshot-holos berkeley edu 2015-04-30 08-51-00](https://cloud.githubusercontent.com/assets/2523089/7416738/49be773a-ef16-11e4-9c53-01e78fac45b4.png)
Holos version of the Compare's legend does not size properly. The tool is unusable as is so needs to be fixed prior to Tuesday 5/5.

Here's what it should look like (taken from Stamen github site):
![screenshot-stamen github io 2015-04-30 08-58-33](https://cloud.githubusercontent.com/assets/2523089/7416862/2b80206a-ef17-11e4-86c4-026950c84299.png)
 So enlarge the search elements so we can see their color swatches, name and drag/drop handles.

**Comment by standardpixel** [comment]
@mkoo Id be happy to help troubleshoot this. How can I get to a place where I can see it in this state myself.

**Comment by shoeswat** [comment]
You can see the problem if you launchholos.berkeley.edu/compareand the
githib pages stamen page

Try adding a layer. The entire dragdrop item doesnt show in ours.

@mkoo <https://github.com/mkoo> Id be happy to help troubleshoot this. How
can I get to a place where I can see it in this state myself.

—
Reply to this email directly or view it on GitHub
<https://github.com/stamen/ecoengine/issues/156#issuecomment-98005465>.

**Comment by shoeswat** [comment]
Ex. Taricha torosa

You can see the problem if you launchholos.berkeley.edu/compareand the
githib pages stamen page

Try adding a layer. The entire dragdrop item doesnt show in ours.

@mkoo <https://github.com/mkoo> Id be happy to help troubleshoot this. How
can I get to a place where I can see it in this state myself.

—
Reply to this email directly or view it on GitHub
<https://github.com/stamen/ecoengine/issues/156#issuecomment-98005465>.

**Comment by standardpixel** [comment]
I just committed a min-height to the scss file in the `master` branch. It seems like there are cases where no label will be set. This will make sure there is still a placeholder if there is no label

**Comment by danrademacher** [comment]
@shoeswat for quick reference, you can see that change here: https://github.com/stamen/ecoengine-compare/commit/6712c40276d1838fb909a4d21cc0f9f7871d57dc#diff-b1ccd74920d712d955af577292ddcca5R168

**Comment by shoeswat** [comment]
@standardpixel still doesn't fix the problem completely. Search Taricha torosa on dev-holos. The draggable box waits until everything is loaded. I think replacing the line to
height: auto;
Should work but I'm working on getting my local copy up for testing.

**Comment by shoeswat** [comment]
i overrode the compiled css with another style sheet (not ideal) and resolved some class conflicts. thanks @postfalk for the help
